###
@user_id = 4c4b8389-886e-4461-9078-664d5cbd7d3f
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzY3MtZ2FtZS1zZXJ2aWNlcyIsInN1YiI6IjRjNGI4Mzg5LTg4NmUtNDQ2MS05MDc4LTY2NGQ1Y2JkN2QzZiIsImV4cCI6MTc2MzAyOTA1OSwiaWF0IjoxNzYzMDI1NDU5LCJqdGkiOiI5NzY5NjIwMy05NjgzLTRiZDctOTI5MS1iZGVjZjdkOWU3MTciLCJ1c2VyX2lkIjoiNGM0YjgzODktODg2ZS00NDYxLTkwNzgtNjY0ZDVjYmQ3ZDNmIiwicm9sZSI6InBsYXllciIsInRva2VuIjoiN2I1YjA5YjAtYTVkZi00OTAwLThjZDYtZjQxOWQ1ZTQzMjk4In0.0KDAsKaQK5ACQXEGRYdD3bN0QGBWOkjO614FD7ieckA

POST http://localhost:8080/api/v1/user/logout
Accept: application/json
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{access_token}}
