###
@user_id = 4c4b8389-886e-4461-9078-664d5cbd7d3f
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzY3MtZ2FtZS1zZXJ2aWNlcyIsInN1YiI6IjRjNGI4Mzg5LTg4NmUtNDQ2MS05MDc4LTY2NGQ1Y2JkN2QzZiIsImV4cCI6MTc2MzYzMDIxOSwiaWF0IjoxNzYzMDI1NDE5LCJqdGkiOiI3YjViMDliMC1hNWRmLTQ5MDAtOGNkNi1mNDE5ZDVlNDMyOTgiLCJ1c2VyX2lkIjoiNGM0YjgzODktODg2ZS00NDYxLTkwNzgtNjY0ZDVjYmQ3ZDNmIiwicm9sZSI6InBsYXllciIsInRva2VuIjoiN2I1YjA5YjAtYTVkZi00OTAwLThjZDYtZjQxOWQ1ZTQzMjk4In0.kGFrnBONVWCWlwX75sGgcjymimlPsS5xxRVVUfL9NZk

@client_id = game-client-id
@client_signature = HSSHSP1EqL8DQaYodmO3xIFXG/XHl460o7Hcn5uWv6g=

POST http://localhost:8080/api/v1/auth/refresh
Accept: application/json
Content-Type: application/json; charset=utf-8
X-Client-ID: {{client_id}}
X-Client-Signature: Client {{client_signature}}

{
    "user_id": "{{user_id}}",
    "refresh_token": "{{refresh_token}}"
}
