###
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json; charset=utf-8
X-Client-ID: game-client-id
X-Client-Signature: Client HSSHSP1EqL8DQaYodmO3xIFXG/XHl460o7Hcn5uWv6g=

{
    "username": "user4557",
    "password": "Passw0rd!"
}

# # Expected Response 200 -- OK
# {
#     "return_code": 1,
#     "return_message": "Success",
#     "data": {
#         "user_id": "<user-uuid>",
#         "username": "<username>",
#         "email": "<email>",

#         "display_name": "<display-name>",
#         "avatar_url": "<avatar-url>",
#         "status": "<user-status>",

#         "player_id": "<player-uuid>",

#         "token_type": "Bearer",
#         "access_token": "<jwt-access-token>",
#         "expires_in": <access-token-expiry-in-seconds>,
#         "refresh_token": "<jwt-refresh-token>"
#     }
# }

# # Expected Response 401 -- Unauthorized
# {
#     "return_code": -100,
#     "return_message": "Signature / Credentials invalid"
# }

# # Expected Response 400 -- Bad Request
# {
#     "return_code": -2,
#     "return_message": "Invalid request"
# }

# # Expected Response 404 -- Not Found
# {
#     "return_code": -200,
#     "return_message": "User / Player not found"
# }

# {
#     "return_code": -106,
#     "return_message": "Account suspended / banned"
# }

# # Expected Response 429 -- Too Many Requests
# {
#     "return_code": -203,
#     "return_message": "Too many login attempts"
# }
